col_classes = c("character", "character", rep("numeric", 7))
data <- read.csv("household_power_consumption.txt", colClasses = col_classes, na.strings=c("?"), sep=";")
data <- within(data, DateTime <- paste(Date, Time, sep=" "))
data$DateTime = as.POSIXct(strptime(data$DateTime, format = "%d/%m/%Y %H:%M:%S"))
data = subset(data, DateTime >= as.POSIXct("2007-02-01") & DateTime < as.POSIXct("2007-02-03"))
png(filename="plot2.png", width = 480, height = 480)
hist(as.numeric(data$Global_active_power), col="black")
dev.off()